import random
from word_frequency import unique_words, frequency, histogram

def stoch(histogram):
    '''
    Stochastic sampling means taking an element from a given collection 
    at random based on it's weight
    Returns a random word 
    '''

    frequency = 0
    total_tokens = len(histogram)
    random_integer = random.randint(1,total_tokens)

    for key,value in histogram.items():
        # add frequency to determine range 
        frequency += value
        # check if word is within range 
        if frequency >= random_integer:
            # return the word 
            return key

'''
calculate range
add frequency to determine range 
see if word is in that range 

take random number 
find word at the index generated by random number 
return random word 
'''